apiVersion: v1
kind: Pod
metadata:
   name: label-test
   labels:
      env: testing
      team: randd
      purpose: learning
spec:
   containers:
      - name: cuda-container
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
        resources:
          limits:
            cpu: "500Mi"
            
  

