apiVersion: v1
kind: Pod
metadata:
   name: label-test
   labels:
      ## Below are labels
      env: testing
      owner: pavan
      team: randd
spec:
   containers:
      - name: kuard
        image: "gcr.io/kuar-demo/kuard-amd64:1"
        ports:
         - containerPort: 8080
           name: http
           protocol: TCP
            
  

